services:
  app:
    build: .
    image: blk-hacking-ind-chetan-dhanjal
    container_name: self-savings-planner
    ports:
      - "5477:5477"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    restart: unless-stopped
